whoisData:
  apikey: at_Oj1aihFSRVU0LbyqZBLnl0PhM2Zan

shodanData:
  apikey: jLcUwcGmyoMnyRW5f8SyrB5U85ztyD0i

farsightData:
  apikey: 55bccaf382c8e595b6ce05e779c9b61165cb70391cc9e9d930871596ee39fd75
  
  
IOC:
  types:
    - IP
    - SPort
    - DPort
    - Email
    - Host
    - URL
    - Hash
    - BTC
    - ASN
    - MAC
    - BGPath
    - SSID
    - Country
    - Domain
    - User
    - Subnet
    - Whois
    - Ports
    - Registrar
    - Nameserver
    - MailServer
    - CybexCount
    - CybexRelated


  enrichments:
    IP:
      - asn
      - gip
      - hostname
      - whois
      - cybexCount
      - cybexRelated
      - netblock
      - ports

    SPort:
      - none

    DPort:
      - none

    Email:
      - deconstructEmail
      - cybexRelated
      - cybexCount

    Host:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers
      - cybexRelated
      - cybexCount
      - pdns

    URL:
      - enrichURL
      - cybexRelated
      - cybexCount
    
    Domain:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers
      - cybexRelated
      - cybexCount

    Hash:
      - cybexRelated
      - cybexCount

    BTC:
      - cybexRelated
      - cybexCount

    ASN:
      - cybexRelated
      - cybexCount

    MAC:
      - none

    BGPath:
      - none

    SSID:
      - none
    
    Country:
      - none

    User:
      - none

    Subnet:
      - none

    Whois:
      - none

    Ports:
      - none

    Registrar: 
      - none

    Nameserver: 
      - none

    MailServer: 
      - none

    CybexCount:
      - none

    CybexRelated:
      - none

    Other:
      - none
