whoisData:
  apikey: at_dE3c8tVnBieCdGwtzUiOFFGfuCQoz

shodanData:
  apikey: jLcUwcGmyoMnyRW5f8SyrB5U85ztyD0i

farsightData:
  apikey: 55bccaf382c8e595b6ce05e779c9b61165cb70391cc9e9d930871596ee39fd75
  
  
IOC:
  types:
    - IP
    - SPort
    - DPort
    - Email
    - Host
    - URL
    - Hash
    - BTC
    - ASN
    - MAC
    - BGPath
    - SSID
    - Country


  enrichments:
    IP:
      - asn
      - gip
      - hostname
      - whois
      - cybex

    SPort:
      - na
      - none

    DPort:
      - na
      - none

    Email:
      - na
      - none

    Host:
      - whois
      - none

    URL:
      - na
      - none

    Hash:
      - na
      - none

    BTC:
      - na
      - none

    ASN:
      - na
      - none

    MAC:
      - na
      - none

    BGPath:
      - na 
      - none

    SSID:
      - na
      - none
    
    Country:
      - na
      - none
