whoisData:
  apikey: at_Oj1aihFSRVU0LbyqZBLnl0PhM2Zan

shodanData:
  apikey: jLcUwcGmyoMnyRW5f8SyrB5U85ztyD0i

farsightData:
  apikey: 55bccaf382c8e595b6ce05e779c9b61165cb70391cc9e9d930871596ee39fd75
  
  
IOC:
  types:
    - IP
    - SPort
    - DPort
    - Email
    - Host
    - URL
    - Hash
    - BTC
    - ASN
    - MAC
    - BGPath
    - SSID
    - Country
    - Domain


  enrichments:
    IP:
      - asn
      - gip
      - hostname
      - whois
      - cybex
      - netblock
      - ports

    SPort:
      - none

    DPort:
      - none

    Email:
      - deconstructEmail
      - none

    Host:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers

    URL:
      - enrichURL
    
    Domain:
      - whois
      - resolveHost
      - nameservers
      - registrar
      - mailservers

    Hash:
      - none

    BTC:
      - none

    ASN:
      - none

    MAC:
      - none

    BGPath:
      - none

    SSID:
      - none
    
    Country:
      - none

   
